apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.project_name | replace(' ','') }}
  description: ${{ values.description | dump }}
  annotations:
    backstage.io/techdocs-ref: dir:.
    ubilityai.com/cluster-name: ${{ values.project_name | lower }}
  infrastructure: aks
  tags:
    - aks
  links:
    - url: https://portal.azure.com/#@testsrack.com/resource/subscriptions/${{ values.subscription_id }}/resourceGroups/${{ values.resource_group }}/providers/Microsoft.ContainerService/managedClusters/${{ values.project_name | lower }}/overview
      title: View AKS on Azure Portal
      icon: dashboard
      type: aks-cluster
spec:
  type: AKS
  lifecycle: created
  owner: ${{ values.owner | dump }}
